[openai]
key = ""  # Acquire through https://platform.openai.com
api_base = ""  # The base URL for your Azure OpenAI resource. e.g. "https://<your resource name>.openai.azure.com"

[gitlab]
# Gitlab personal access token
personal_access_token = ""